"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import "./citypulse.css";
import { CITY_PULSE_CONFIG, LEVELS } from "@/config/civic";
import { TESTIDS } from "@/config/testids";
import type { Hotspot } from "@/contracts/hotspots";
import { AuthorityApiError, authorityApi } from "@/lib/authority/api";
import { dateTime } from "@/lib/authority/format";
import { HotspotMap } from "./HotspotMap";
import { HotspotDetail, HotspotList } from "./HotspotPanels";

type Load =
  | { state: "loading" }
  | { state: "error"; error: AuthorityApiError }
  | { state: "ready"; hotspots: Hotspot[] };

function toApiError(cause: unknown): AuthorityApiError {
  return cause instanceof AuthorityApiError
    ? cause
    : new AuthorityApiError(
        cause instanceof Error ? cause.message : "Something went wrong.",
        "INTERNAL",
        0,
      );
}

const isAuthError = (error: AuthorityApiError) =>
  error.status === 401 || error.status === 403;

/** Most severe first, then by trend. */
function sorted(rows: Hotspot[]): Hotspot[] {
  return [...rows].sort(
    (a, b) =>
      LEVELS.indexOf(b.severity) - LEVELS.indexOf(a.severity) ||
      b.trend_percent - a.trend_percent,
  );
}

function latestGenerated(rows: Hotspot[]): string | null {
  return rows.reduce<string | null>(
    (latest, row) =>
      !latest || row.generated_at > latest ? row.generated_at : latest,
    null,
  );
}

function SignInAgain() {
  return (
    <>
      {" "}
      <Link href="/authority/login">Sign in again</Link>
    </>
  );
}

export function CityPulse() {
  const [load, setLoad] = useState<Load>({ state: "loading" });
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [regenError, setRegenError] = useState<AuthorityApiError | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);

  const show = useCallback((rows: Hotspot[]) => {
    const next = sorted(rows);
    setLoad({ state: "ready", hotspots: next });
    setSelectedId((current) =>
      current && next.some((h) => h.id === current)
        ? current
        : (next[0]?.id ?? null),
    );
  }, []);

  const fetchHotspots = useCallback(async () => {
    setLoad({ state: "loading" });
    try {
      const rows = await authorityApi.hotspots();
      show(rows);
      setGeneratedAt(latestGenerated(rows));
    } catch (cause) {
      setLoad({ state: "error", error: toApiError(cause) });
    }
  }, [show]);

  useEffect(() => {
    let active = true;
    authorityApi
      .hotspots()
      .then((rows) => {
        if (!active) return;
        show(rows);
        setGeneratedAt(latestGenerated(rows));
      })
      .catch((cause: unknown) => {
        if (active) setLoad({ state: "error", error: toApiError(cause) });
      });
    return () => {
      active = false;
    };
  }, [show]);

  async function regenerate() {
    setBusy(true);
    setRegenError(null);
    try {
      const result = await authorityApi.regenerateHotspots();
      show(result.hotspots);
      setGeneratedAt(result.generated_at);
    } catch (cause) {
      setRegenError(toApiError(cause));
    } finally {
      setBusy(false);
    }
  }

  const hotspots = load.state === "ready" ? load.hotspots : [];
  const selected = hotspots.find((h) => h.id === selectedId) ?? null;

  return (
    <div className="cp">
      <header className="cp-header">
        <div className="page-heading cp-heading">
          <p className="eyebrow">Authority workspace</p>
          <h1>City Pulse</h1>
          <p>
            Clusters of new reports compared with the previous{" "}
            {CITY_PULSE_CONFIG.baseline_window_hours} hours, generated by
            CivicPulse from citizen reports. Recommendations only — staff
            decide.
          </p>
        </div>
        <div className="cp-actions">
          <button
            type="button"
            className="ap-button"
            onClick={() => void regenerate()}
            disabled={busy}
            aria-busy={busy}
            data-testid={TESTIDS.hotspotRegenerate}
          >
            {busy ? "Regenerating…" : "Regenerate"}
          </button>
          {generatedAt && (
            <span className="ap-muted cp-generated" role="status">
              Generated at {dateTime(generatedAt)}
            </span>
          )}
        </div>
      </header>

      {regenError && (
        <p className="cp-alert" role="alert">
          Regenerate failed: {regenError.message}
          {isAuthError(regenError) && <SignInAgain />}
        </p>
      )}

      <div className="cp-layout">
        <HotspotMap
          hotspots={hotspots}
          selectedId={selectedId}
          onSelect={setSelectedId}
        />

        <div className="cp-side">
          {load.state === "loading" && (
            <section className="state-panel" role="status">
              Loading hotspots…
            </section>
          )}
          {load.state === "error" && (
            <section className="state-panel" role="alert">
              <span className="ap-error">{load.error.message}</span>
              {isAuthError(load.error) ? (
                <SignInAgain />
              ) : (
                <button type="button" onClick={() => void fetchHotspots()}>
                  Retry
                </button>
              )}
            </section>
          )}
          {load.state === "ready" && hotspots.length === 0 && (
            <section className="state-panel" role="status">
              <h2>No active hotspots right now</h2>
              <p>
                A hotspot appears when at least{" "}
                {CITY_PULSE_CONFIG.min_current_count} open issues of the same
                category cluster within ~{CITY_PULSE_CONFIG.cluster_eps_m} m in
                the last {CITY_PULSE_CONFIG.current_window_hours} hours. Use
                Regenerate to recompute from the latest reports.
              </p>
            </section>
          )}
          {load.state === "ready" && hotspots.length > 0 && (
            <>
              <h2 className="cp-list-title">
                {hotspots.length} active{" "}
                {hotspots.length === 1 ? "hotspot" : "hotspots"}
              </h2>
              <HotspotList
                hotspots={hotspots}
                selectedId={selectedId}
                onSelect={setSelectedId}
              />
              {selected && <HotspotDetail hotspot={selected} />}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
